Authenticatie endpoints
EmJee1/cmelse pull request #5
Opened 2021-12-22 18:29 UTC by EmJee1

#### Wat doet dit PR

Het voegt het `login` en `register` endpoint toe waarop gebruikers kunnen registreren en inloggen.

#### Hoe test je dit PR

- Maak een `POST` request naar http://localhost:3001/authentication/register
- Controleer dat de body validatie werkt (alleen geldig emailadres en alle vereiste velden)
- Maak nu een request met geldige data en controleer dat de gebruiker aangemaakt wordt en een token teruggestuurd wordt.
- Log nu in met het aangemaakte account op http://localhost:3001/authentication/login
- Controleer dat je alleen een token terugkrijgt als je de juiste credentials gebruikt
- Controleer ook dat je kan inloggen met zowel je `username` als `password` (stop deze in de body met de key `identifier`

2021-12-22 18:30 UTC, EmJee1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Login en registratie endpoints](https://trello.com/c/vfrFUCH2/15-login-en-registratie-endpoints)

2021-12-22 18:30 UTC, EmJee1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Login en registratie endpoints](https://trello.com/c/vfrFUCH2/15-login-en-registratie-endpoints)

2021-12-26 10:27 UTC, sharpTshark requested changes
# secretOrPrivateKey must have a value

ik krijg 2 de zelfde errors zowel bij login als register.

![image](https://user-images.githubusercontent.com/71552553/147405363-a279b8fe-30fc-44f1-9e19-794bf80a0244.png)

bij register word er wel de juiste data aangemaakt in mongo.

2021-12-27 15:27 UTC, EmJee1 commented
> # secretOrPrivateKey must have a value
> 
> ik krijg 2 de zelfde errors zowel bij login als register.
> 
> ![image](https://user-images.githubusercontent.com/71552553/147405363-a279b8fe-30fc-44f1-9e19-794bf80a0244.png)
> 
> bij register word er wel de juiste data aangemaakt in mongo.
> 

Ah ja dan moet je je environment (`.env`) file aanvullen met de nieuwe data. Die staat als het goed is in de `.env.example`

2022-01-06 07:58 UTC, EmJee1 commented
Merge in overleg met @sharpTshark

2022-01-06 07:58 UTC, merged